version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:8f:4a:57:f3:d0:7d:ce:70:67:11:11:09:0b:4f:dc"
      - run: curl -LO https://deployer.org/deployer.phar
      - run: sudo mv deployer.phar /usr/local/bin/dep
      - run: sudo chmod +x /usr/local/bin/dep
      - checkout
      - run: dep deploy
